wandb_version: 1

save_path:
  desc: null
  value: ./checkpoint/model/llama3.1-8b-sft/
save_steps:
  desc: null
  value: 20
logging_steps:
  desc: null
  value: 1
eval_steps:
  desc: null
  value: -1
ckpt_path:
  desc: null
  value: ./checkpoint/opt/llama3.1-8b-sft/
max_ckpt_num:
  desc: null
  value: 3
max_ckpt_mem:
  desc: null
  value: 100000000.0
load_checkpoint:
  desc: null
  value: false
micro_train_batch_size:
  desc: null
  value: 1
train_batch_size:
  desc: null
  value: 8
max_norm:
  desc: null
  value: 1.0
gradient_checkpointing:
  desc: null
  value: true
seed:
  desc: null
  value: 42
local_rank:
  desc: null
  value: 0
zero_stage:
  desc: null
  value: 3
bf16:
  desc: null
  value: true
zpg:
  desc: null
  value: 1
adam_offload:
  desc: null
  value: false
flash_attn:
  desc: null
  value: true
grad_accum_dtype:
  desc: null
  value: null
disable_trace_cache:
  desc: null
  value: false
gradient_checkpointing_use_reentrant:
  desc: null
  value: false
disable_fast_tokenizer:
  desc: null
  value: true
max_epochs:
  desc: null
  value: 5
aux_loss_coef:
  desc: null
  value: 0
pretrain:
  desc: null
  value: /data/zecheng/hf_models/Meta-Llama-3.1-8B-Instruct
learning_rate:
  desc: null
  value: 5.0e-06
pretrain_mode:
  desc: null
  value: false
lr_scheduler:
  desc: null
  value: cosine_with_min_lr
l2:
  desc: null
  value: 0
adam_betas:
  desc: null
  value:
  - 0.9
  - 0.95
load_in_4bit:
  desc: null
  value: false
lora_rank:
  desc: null
  value: 32
lora_alpha:
  desc: null
  value: 16
target_modules:
  desc: null
  value: all-linear
lora_dropout:
  desc: null
  value: 0
packing_samples:
  desc: null
  value: true
dataset:
  desc: null
  value: /data/zecheng/lcm_stack/dataset/training_data/dev_Qwen_query_answer_gen
dataset_probs:
  desc: null
  value: '1.0'
num_process:
  desc: null
  value: 96
train_split:
  desc: null
  value: train
eval_split:
  desc: null
  value: test
return_eval:
  desc: null
  value: false
input_key:
  desc: null
  value: instruction_str
output_key:
  desc: null
  value: pred_str
input_template:
  desc: null
  value: 'User: {}

    Assistant: '
apply_chat_template:
  desc: null
  value: true
tokenizer_chat_template:
  desc: null
  value: null
max_samples:
  desc: null
  value: 100000000.0
max_len:
  desc: null
  value: 64000
ring_attn_size:
  desc: null
  value: 1
ring_head_stride:
  desc: null
  value: 1
use_wandb:
  desc: null
  value: f81f2a236e712350a0ec153e02f43d1366c856a5
wandb_org:
  desc: null
  value: null
wandb_group:
  desc: null
  value: null
wandb_project:
  desc: null
  value: debug_openrlhf_train_sft
wandb_run_name:
  desc: null
  value: llama3.1-8b-sft-vanilla
use_tensorboard:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.4
    framework: huggingface
    huggingface_version: 4.44.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1729873912
    t:
      1:
      - 1
      - 5
      - 11
      - 30
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 105
      2:
      - 1
      - 5
      - 11
      - 30
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 105
      3:
      - 7
      - 13
      - 16
      - 23
      - 66
      4: 3.10.14
      5: 0.17.4
      6: 4.44.2
      8:
      - 2
      - 5
      13: linux-x86_64
    m:
    - 1: train/global_step
      6:
      - 3
    - 1: eval/global_step
      6:
      - 3
    - 1: train/gpt_loss
      5: 1
      6:
      - 1
    - 1: train/loss_mean
      5: 1
      6:
      - 1
    - 1: train/lr
      5: 1
      6:
      - 1
